# Generated by Django 3.0.5 on 2020-06-18 12:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('projects', '0002_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('images', wagtail.core.fields.StreamField([('images', wagtail.core.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock(help_text='Upload images', required=True))]))], blank=True, null=True)),
                ('project_description', wagtail.core.fields.RichTextField()),
                ('project_information', wagtail.core.fields.RichTextField()),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.ProjectCategory')),
            ],
            options={
                'verbose_name': 'ProjectDetail page',
                'verbose_name_plural': 'ProjectDetail pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
