# Generated by Django 3.0.5 on 2020-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdetailpage_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
