# Generated by Django 3.0.5 on 2020-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200619_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetailpage',
            name='client',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectdetailpage',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
