# Generated by Django 3.0.5 on 2020-06-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200619_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetailpage',
            name='client',
        ),
    ]
