# Generated by Django 3.0.5 on 2020-06-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_aboutpage_team'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='about.BannerSnippet'),
        ),
    ]
