# Generated by Django 3.0.5 on 2020-06-10 10:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicespage_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Overwrites the default title', max_length=50)),
                ('tabs', wagtail.core.fields.StreamField([('tabs', wagtail.core.blocks.StructBlock([('tab_title', wagtail.core.blocks.CharBlock(help_text='Add your title', max_length=30, required=True)), ('tab_content', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicespage',
            name='tabs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='services.ProductInfoSnippet'),
        ),
    ]
