# Generated by Django 3.0.5 on 2020-06-15 11:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200615_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='text',
            field=wagtail.core.fields.RichTextField(default='text'),
        ),
    ]
