# Generated by Django 3.0.5 on 2020-06-15 12:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicespage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='quotes',
            field=wagtail.core.fields.StreamField([('quotes', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(required=True)), ('author_name', wagtail.core.blocks.CharBlock(max_length=30, required=True))]))], blank=True, null=True),
        ),
    ]
