# Generated by Django 3.0.5 on 2020-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
