# Generated by Django 3.0.5 on 2020-06-08 23:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='card_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slides',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='video_section_subscribe',
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Add additional text', max_length=100, required=True)), ('video_link', wagtail.core.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='counter',
            field=wagtail.core.fields.StreamField([('counter', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add additional title', max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project',
            field=wagtail.core.fields.StreamField([('project', wagtail.core.blocks.StructBlock([('category', wagtail.core.blocks.CharBlock(help_text='Add additional category', max_length=100, required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Add additional title', max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.core.fields.StreamField([('services', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Add additional text', max_length=100, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True),
        ),
    ]
