# Generated by Django 3.0.5 on 2020-06-09 00:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200608_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add additional title', max_length=100, required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Add additional text', max_length=100, required=True)), ('video_link', wagtail.core.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True),
        ),
    ]
