# Generated by Django 3.0.5 on 2020-06-09 05:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0003_auto_20200608_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='counter_background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature',
            field=wagtail.core.fields.StreamField([('feature', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add additional title', max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True)), ('icon', wagtail.core.blocks.CharBlock(max_length=50, required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='counter',
            field=wagtail.core.fields.StreamField([('counter', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add additional text', required=True)), ('thousand', wagtail.core.blocks.BooleanBlock())]))], blank=True, null=True),
        ),
    ]
