# Generated by Django 3.0.5 on 2020-06-09 06:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0007_auto_20200608_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page', 'verbose_name_plural': 'Home pages'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='counter_background',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature',
        ),
        migrations.CreateModel(
            name='FeatureSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('counter', wagtail.core.fields.StreamField([('counter', wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.IntegerBlock(required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add additional text', required=True)), ('delay', wagtail.core.blocks.IntegerBlock(default=0, required=False)), ('speed', wagtail.core.blocks.IntegerBlock(required=True)), ('thousand', wagtail.core.blocks.BooleanBlock(default=False, required=False))]))], blank=True, null=True)),
                ('feature', wagtail.core.fields.StreamField([('feature', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add additional title', max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True)), ('icon', wagtail.core.blocks.CharBlock(max_length=50, required=True))]))], blank=True, null=True)),
                ('counter_background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.FeatureSnippet'),
        ),
    ]
