# Generated by Django 3.0.5 on 2020-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200619_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsnippet',
            name='title',
            field=models.CharField(default='Navigation', max_length=50),
        ),
    ]
