# Generated by Django 3.0.5 on 2020-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_navigationsnippet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsnippet',
            name='footer_text',
            field=models.TextField(),
        ),
    ]
