# Generated by Django 3.0.5 on 2020-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200619_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsnippet',
            name='facebook',
            field=models.URLField(default='https://facebook.com'),
        ),
    ]
