# Generated by Django 3.0.5 on 2020-06-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('about', '0002_aboutpage_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Overwrites the default title', max_length=50)),
                ('header_text', models.CharField(help_text='Overwrites the default title', max_length=50)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='about.HeaderSnippet'),
        ),
    ]
