# Generated by Django 3.0.5 on 2020-06-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('about', '0003_auto_20200609_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderSnippet',
            new_name='BannerSnippet',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='header',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='bannersnippet',
            old_name='header_image',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='bannersnippet',
            old_name='header_text',
            new_name='banner_text',
        ),
    ]
