# Generated by Django 3.0.5 on 2020-06-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('about', '0005_aboutussnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussnippet',
            name='bg_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
