# Generated by Django 3.0.5 on 2020-06-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_aboutussnippet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='about.AboutUsSnippet'),
        ),
    ]
