# Generated by Django 3.0.5 on 2020-06-09 09:01

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_aboutpage_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Overwrites the default title', max_length=50)),
                ('testimonials', wagtail.core.fields.StreamField([('testimonials', wagtail.core.blocks.StructBlock([('feedback', wagtail.core.blocks.TextBlock(help_text='Add Client Feedback', required=True)), ('client_name', wagtail.core.blocks.CharBlock(help_text='Add Client Name', max_length=40, required=True)), ('Date', wagtail.core.blocks.DateBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True)),
            ],
        ),
    ]
