# Generated by Django 3.0.5 on 2020-06-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_testimonialsnippet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About page', 'verbose_name_plural': 'About pages'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='testimonials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='about.TestimonialSnippet'),
        ),
    ]
