# Generated by Django 3.0.5 on 2020-06-09 09:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20200609_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsnippet',
            name='testimonials',
            field=wagtail.core.fields.StreamField([('testimonials', wagtail.core.blocks.StructBlock([('feedback', wagtail.core.blocks.TextBlock(help_text='Add Client Feedback', required=True)), ('client_name', wagtail.core.blocks.CharBlock(help_text='Add Client Name', max_length=40, required=True)), ('date', wagtail.core.blocks.DateBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True),
        ),
    ]
