# Generated by Django 3.0.5 on 2020-06-09 09:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20200609_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='clients',
            field=wagtail.core.fields.StreamField([('clients', wagtail.core.blocks.StructBlock([('img', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True))]))], blank=True, null=True),
        ),
    ]
