# Generated by Django 3.0.5 on 2020-06-09 10:11

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_aboutpage_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Overwrites the default title', max_length=50)),
                ('member', wagtail.core.fields.StreamField([('member', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock(help_text='Upload slide image', required=True)), ('name', wagtail.core.blocks.CharBlock(max_length=30, required=True)), ('position', wagtail.core.blocks.CharBlock(max_length=30, required=True)), ('facebook', wagtail.core.blocks.URLBlock()), ('linkedin', wagtail.core.blocks.URLBlock()), ('instagram', wagtail.core.blocks.URLBlock())]))], blank=True, null=True)),
            ],
        ),
    ]
