# Generated by Django 3.0.5 on 2020-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200501_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
                ('quote', models.CharField(max_length=250)),
                ('photo', models.ImageField(default='../static/img/customer/customer-1.png', upload_to='customer/')),
            ],
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='profile_link',
        ),
        migrations.AddField(
            model_name='team_member',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team_member',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team_member',
            name='twitter_profile',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='photo',
            field=models.ImageField(default='../static/img/customer/customer-1.png', upload_to='member/'),
        ),
    ]
