# Generated by Django 3.0.5 on 2020-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20200501_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quote',
            field=models.TextField(),
        ),
    ]
