# Generated by Django 3.0.5 on 2020-05-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_customer_customer_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mark',
            new_name='rating',
        ),
    ]
